name: Testing pipeline

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  centos_unit_test:
    name: CentOS ${{ matrix.centos_ver }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        centos_ver: [8]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          context: .
          file: ./dockerfiles/centos${{ matrix.centos_ver }}.Dockerfile
          tags: centos-${{ matrix.centos_ver }}

      - name: Run unit tests in container
        run: |
          docker run centos-${{ matrix.centos_ver }} make test

  fedora_unit_test:
    name: Fedora ${{ matrix.fedora_ver }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fedora_ver: [34]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          context: .
          file: ./dockerfiles/fedora${{ matrix.fedora_ver }}.Dockerfile
          tags: fedora-${{ matrix.fedora_ver }}

      - name: Run unit tests in container
        run: |
          docker run fedora-${{ matrix.fedora_ver }} make test